# Pandas
Learn to work with tables using short examples. Run cells from top to bottom. You need pandas. Pokémon values are practice data.

## Contents
1. Setup and Series
2. Creating DataFrames
3. Adding and Updating Data
4. Reading CSV Data
5. Inspecting and Selecting Data
6. Filtering Rows
7. Aggregations
8. Grouping Data
9. Cleaning and Exporting Data
10. Practice

## 1. Setup and Series
A Series is one column of values with labels. Create it from a list or dictionary. `.loc` selects by label; `.iloc` selects by position, starting at zero.

In [1]:
import pandas as pd
from io import StringIO

series = pd.Series([100, 200, 300, 400, 500], index=['a', 'b', 'c', 'd', 'e'])
print(series.loc['c'])
print(series.iloc[2])

300
300

In [2]:
calories = pd.Series({'Day1': 1750, 'Day2': 2100, 'Day3': 1750, 'Day4': 2000, 'Day5': 1800})
calories.loc['Day2'] += 500
calories.iloc[3] -= 200
print(calories)
print('Above 2000:', calories[calories > 2000])

Day1    1750
Day2    2600
Day3    1750
Day4    1800
Day5    1800
dtype: int64
Above 2000: Day2    2600
dtype: int64

## 2. Creating DataFrames
A DataFrame is a table with rows and columns. Each column can have a different type. Column lists must have the same length. Put a DataFrame last in a Jupyter cell to display it as a table.

In [3]:
team_data = {
    'Name': ['Pikachu', 'Bulbasaur', 'Squirtle'],
    'Level': [12, 10, 11],
}
team = pd.DataFrame(team_data, index=['a', 'b', 'c'])
team

        Name  Level
a    Pikachu     12
b  Bulbasaur     10
c   Squirtle     11

## 3. Adding and Updating Data
Assign a new column to the DataFrame. Changing the original dictionary does not add a column to an existing DataFrame. Use `.loc[row, column]` to update a cell and `pd.concat()` to add rows.

In [4]:
team['Role'] = ['Attacker', 'Support', 'Defender']
team.loc['a', 'Level'] = 13
new_member = pd.DataFrame({'Name': ['Charmander'], 'Level': [9], 'Role': ['Attacker']}, index=['d'])
team = pd.concat([team, new_member])
team

         Name  Level      Role
a     Pikachu     13  Attacker
b   Bulbasaur     10   Support
c    Squirtle     11  Defender
d  Charmander      9  Attacker

## 4. Reading CSV Data
`pd.read_csv()` reads CSV data. `index_col` chooses the row labels. This example includes CSV text. To use a file, try `pd.read_csv('pokemon.csv', index_col='No')`.

In [5]:
csv_data = """No,Name,Type1,Type2,Height,Weight,Legendary
1,Bulbasaur,Grass,Poison,0.7,7.0,False
6,Charizard,Fire,Flying,1.7,90.0,False
9,Blastoise,Water,,1.6,85.0,False
25,Pikachu,Electric,,0.4,6.0,False
130,Gyarados,Water,Flying,6.5,235.0,False
144,Articuno,Ice,Flying,1.7,55.0,True
"""
pokemon_df = pd.read_csv(StringIO(csv_data), index_col='No')
pokemon_df

          Name     Type1   Type2  Height  Weight  Legendary
No
1    Bulbasaur     Grass  Poison     0.7     7.0      False
6    Charizard      Fire  Flying     1.7    90.0      False
9    Blastoise     Water     NaN     1.6    85.0      False
25     Pikachu  Electric     NaN     0.4     6.0      False
130   Gyarados     Water  Flying     6.5   235.0      False
144   Articuno       Ice  Flying     1.7    55.0       True

## 5. Inspecting and Selecting Data
Use `head(n)` to preview rows. `shape` shows row and column counts. `columns` lists names, `dtypes` shows types, and `info()` prints a table summary. `to_string(index=False)` prints without row labels.

In [6]:
print(pokemon_df.head(3))
print('Shape:', pokemon_df.shape)
print('Columns:', pokemon_df.columns.tolist())
print(pokemon_df.dtypes)
pokemon_df.info()

         Name  Type1   Type2  Height  Weight  Legendary
No
1   Bulbasaur  Grass  Poison     0.7     7.0      False
6   Charizard   Fire  Flying     1.7    90.0      False
9   Blastoise  Water     NaN     1.6    85.0      False
Shape: (6, 6)
Columns: ['Name', 'Type1', 'Type2', 'Height', 'Weight', 'Legendary']
Name             str
Type1            str
Type2            str
Height       float64
Weight       float64
Legendary       bool
dtype: object
<class 'pandas.DataFrame'>
Index: 6 entries, 1 to 144
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       6 non-null      str
 1   Type1      6 non-null      str
 2   Type2      4 non-null      str
 3   Height     6 non-null      float64
 4   Weight     6 non-null      float64
 5   Legendary  6 non-null      bool
dtypes: bool(1), float64(2), str(3)
memory usage: 399.0 bytes

### Selecting columns and rows
One column name returns a Series; a list of names returns a DataFrame. `set_index()` chooses new row labels. A `.loc` slice includes its ending label; an `.iloc` slice excludes its ending position.

In [7]:
print(pokemon_df['Name'].to_string(index=False))
print(pokemon_df[['Name', 'Type1']])
pokemon_by_name = pokemon_df.set_index('Name')
print(pokemon_by_name.loc['Pikachu'])
print(pokemon_by_name.iloc[0:6:2, 0:2])
print(pokemon_by_name.loc['Charizard':'Blastoise', ['Height', 'Type1']])

No
Bulbasaur
Charizard
Blastoise
  Pikachu
 Gyarados
 Articuno
          Name     Type1
No
1    Bulbasaur     Grass
6    Charizard      Fire
9    Blastoise     Water
25     Pikachu  Electric
130   Gyarados     Water
144   Articuno       Ice
Type1        Electric
Type2             NaN
Height            0.4
Weight            6.0
Legendary       False
Name: Pikachu, dtype: object
           Type1   Type2
Name
Bulbasaur  Grass  Poison
Blastoise  Water     NaN
Gyarados   Water  Flying
           Height  Type1
Name
Charizard     1.7   Fire
Blastoise     1.6  Water

### Handling a missing label
A missing label raises `KeyError`. Change `pokemon_name` below to try another name. The error handler prints a helpful message if the name is missing.

In [8]:
pokemon_name = 'Pikachu'
try:
    print(pokemon_by_name.loc[pokemon_name])
except KeyError:
    print(f'{pokemon_name} is not found in the dataset.')

Type1        Electric
Type2             NaN
Height            0.4
Weight            6.0
Legendary       False
Name: Pikachu, dtype: object

## 6. Filtering Rows
Filter rows with a condition inside `df[...]`. Combine conditions with `&` (AND), `|` (OR), or `~` (NOT). Put each comparison in parentheses.

In [9]:
grass_pokemon = pokemon_df[pokemon_df['Type1'] == 'Grass']
tall_pokemon = pokemon_df[pokemon_df['Height'] > 2.0]
heavy_pokemon = pokemon_df[pokemon_df['Weight'] > 100.0]
print('Grass:', grass_pokemon)
print('Tall:', tall_pokemon)
print('Heavy:', heavy_pokemon)

Grass:          Name  Type1   Type2  Height  Weight  Legendary
No
1   Bulbasaur  Grass  Poison     0.7     7.0      False
Tall:          Name  Type1   Type2  Height  Weight  Legendary
No
130  Gyarados  Water  Flying     6.5   235.0      False
Heavy:          Name  Type1   Type2  Height  Weight  Legendary
No
130  Gyarados  Water  Flying     6.5   235.0      False

In [10]:
water_flying = pokemon_df[(pokemon_df['Type1'] == 'Water') & (pokemon_df['Type2'] == 'Flying')]
print(water_flying)
print(pokemon_df[(pokemon_df['Type1'] == 'Grass') | (pokemon_df['Type1'] == 'Electric')])

         Name  Type1   Type2  Height  Weight  Legendary
No
130  Gyarados  Water  Flying     6.5   235.0      False
         Name     Type1   Type2  Height  Weight  Legendary
No
1   Bulbasaur     Grass  Poison     0.7     7.0      False
25    Pikachu  Electric     NaN     0.4     6.0      False

## 7. Aggregations
Use `mean()`, `min()`, `max()`, and `sum()` to summarize numbers. `count()` counts filled values; `len(df)` counts rows. `describe()` gives a numeric summary.

In [11]:
measurements = pokemon_df[['Height', 'Weight']]
print('Means:', measurements.mean())
print('Minimums:', measurements.min())
print('Maximums:', measurements.max())
print('Non-missing counts:', pokemon_df.count())
print('Rows:', len(pokemon_df))
print(pokemon_df.describe())

Means: Height     2.100000
Weight    79.666667
dtype: float64
Minimums: Height    0.4
Weight    6.0
dtype: float64
Maximums: Height      6.5
Weight    235.0
dtype: float64
Non-missing counts: Name         6
Type1        6
Type2        4
Height       6
Weight       6
Legendary    6
dtype: int64
Rows: 6
         Height      Weight
count  6.000000    6.000000
mean   2.100000   79.666667
std    2.226208   84.355597
min    0.400000    6.000000
25%    0.925000   19.000000
50%    1.650000   70.000000
75%    1.700000   88.750000
max    6.500000  235.000000

### Aggregating one column
Select a column with brackets, such as `df['Height']`. This also works when a column name contains spaces or matches a DataFrame method.

In [12]:
print('Mean height:', pokemon_df['Height'].mean())
print('Total weight:', pokemon_df['Weight'].sum())
print('Recorded primary types:', pokemon_df['Type1'].count())

Mean height: 2.1
Total weight: 478.0
Recorded primary types: 6

## 8. Grouping Data
`groupby()` collects rows with the same group name. Then calculate a summary for each group. `size()` counts rows; `count()` counts filled values in a column.

In [13]:
grouped = pokemon_df.groupby('Type1')
print('Mean height:', grouped['Height'].mean())
print('Total weight:', grouped['Weight'].sum())
print('Group sizes:', grouped.size())
summary = grouped.agg(Count=('Name', 'count'), MeanHeight=('Height', 'mean'), TotalWeight=('Weight', 'sum'))
summary

Mean height: Type1
Electric    0.40
Fire        1.70
Grass       0.70
Ice         1.70
Water       4.05
Name: Height, dtype: float64
Total weight: Type1
Electric      6.0
Fire         90.0
Grass         7.0
Ice          55.0
Water       320.0
Name: Weight, dtype: float64
Group sizes: Type1
Electric    1
Fire        1
Grass       1
Ice         1
Water       2
dtype: int64

          Count  MeanHeight  TotalWeight
Type1
Electric      1        0.40          6.0
Fire          1        1.70         90.0
Grass         1        0.70          7.0
Ice           1        1.70         55.0
Water         2        4.05        320.0

## 9. Cleaning and Exporting Data
Make a copy before cleaning. A missing secondary Pokémon type may mean there is no second type. Choose whether to fill or drop it. Assign cleaning results to a variable to keep them.

In [14]:
cleaned = pokemon_df.copy()
print('Missing values:', cleaned.isna().sum())
without_legendary = cleaned.drop(columns=['Legendary'])
dual_type_only = cleaned.dropna(subset=['Type2'])
filled = cleaned.fillna({'Type2': 'None'})
print(without_legendary.head(2))
print(dual_type_only[['Name', 'Type2']])
print(filled[['Name', 'Type2']])

Missing values: Name         0
Type1        0
Type2        2
Height       0
Weight       0
Legendary    0
dtype: int64
         Name  Type1   Type2  Height  Weight
No
1   Bulbasaur  Grass  Poison     0.7     7.0
6   Charizard   Fire  Flying     1.7    90.0
          Name   Type2
No
1    Bulbasaur  Poison
6    Charizard  Flying
130   Gyarados  Flying
144   Articuno  Flying
          Name   Type2
No
1    Bulbasaur  Poison
6    Charizard  Flying
9    Blastoise    None
25     Pikachu    None
130   Gyarados  Flying
144   Articuno  Flying

### Standardizing text and types
Use `.str` methods to clean text and `replace()` to fix labels. Use `pd.to_numeric()` to convert numeric text. The example adds inconsistent labels, then fixes them.

In [15]:
cleaned.loc[1, 'Type1'] = ' GRASS '
cleaned.loc[6, 'Type1'] = 'Flame'
cleaned['Type1'] = cleaned['Type1'].str.strip().str.capitalize()
cleaned['Type1'] = cleaned['Type1'].replace({'Flame': 'Fire'})
cleaned['Type2'] = cleaned['Type2'].fillna('None').str.strip().str.lower()
cleaned['Height'] = pd.to_numeric(cleaned['Height'])
cleaned['Legendary'] = cleaned['Legendary'].astype('boolean')
cleaned

          Name     Type1   Type2  Height  Weight  Legendary
No
1    Bulbasaur     Grass  poison     0.7     7.0      False
6    Charizard      Fire  flying     1.7    90.0      False
9    Blastoise     Water    none     1.6    85.0      False
25     Pikachu  Electric    none     0.4     6.0      False
130   Gyarados     Water  flying     6.5   235.0      False
144   Articuno       Ice  flying     1.7    55.0       True

**True/False text:** map `'True'` and `'False'` to Boolean values first. Avoid `.astype(bool)` on these strings: both are nonempty, so both become `True`. The CSV example already contains Boolean values.

In [16]:
flag_text = pd.Series(['True', 'False'])
print(flag_text.map({'True': True, 'False': False}).astype('boolean'))

0     True
1    False
dtype: boolean

### Removing duplicates
`drop_duplicates()` removes repeated rows. This example adds a duplicate, then removes it by name. Check that repeated names are really duplicates before deleting them.

In [17]:
with_duplicate = pd.concat([cleaned, cleaned.iloc[[0]]])
cleaned = with_duplicate.drop_duplicates(subset=['Name'], keep='first')
print('Before:', len(with_duplicate), 'After:', len(cleaned))

Before: 7 After: 6

### Exporting CSV
`to_csv()` without a path returns CSV text. To save a file, use `cleaned.to_csv('pokemon_cleaned.csv', index=True, index_label='No')`. Use `index=False` to leave out row labels.

In [18]:
csv_output = cleaned.to_csv(index=True, index_label='No')
print(csv_output)

# Uncomment to save the file:
# cleaned.to_csv('pokemon_cleaned.csv', index=True, index_label='No')

No,Name,Type1,Type2,Height,Weight,Legendary
1,Bulbasaur,Grass,poison,0.7,7.0,False
6,Charizard,Fire,flying,1.7,90.0,False
9,Blastoise,Water,none,1.6,85.0,False
25,Pikachu,Electric,none,0.4,6.0,False
130,Gyarados,Water,flying,6.5,235.0,False
144,Articuno,Ice,flying,1.7,55.0,True

## 10. Practice
1. Create a Series with custom labels and update a value using `.loc`.
2. Select the second value using `.iloc`.
3. Create a DataFrame with names and levels, then add a role column.
4. Add one row using `pd.concat()`.
5. Select a Pokémon by name and select its height and weight.
6. Filter Water-type Pokémon weighing more than 80.
7. Compare row count with the non-missing `Type2` count.
8. Find mean weight and number of Pokémon for each primary type.
9. Fill missing secondary types and remove a deliberately duplicated row.
10. Preview your cleaned data as CSV text; optionally save it to a file.

In [19]:
# Write your practice code here